data_dir: ./api/data
index_dir: ./indices
embedding_model: intfloat/multilingual-e5-base
cross_encoder_model: cross-encoder/ms-marco-MiniLM-L-6-v2
# Ollama settings
ollama_url: http://localhost:11434
ollama_model_name: mistral            # le nom du mod√®le dans Ollama (ex: 'mistral' ou 'mistralai/Mistral-7B-Instruct-v0.2')
